# Generated by Django 4.0.7 on 2022-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_rename_vending_machine_id_items_vending_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
