# Generated by Django 4.0.7 on 2022-09-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('VM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='items',
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='items',
            field=models.ManyToManyField(to='Items.items'),
        ),
    ]
