# Generated by Django 4.0.7 on 2022-09-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('VM', '0002_remove_vendingmachine_items_vendingmachine_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='items',
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Items.items'),
            preserve_default=False,
        ),
    ]
