# Generated by Django 4.0.7 on 2022-09-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VM', '0003_remove_vendingmachine_items_vendingmachine_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='items',
        ),
    ]
