# Generated by Django 4.0.7 on 2022-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VM', '0004_remove_vendingmachine_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
